export const formTemplateDataTags = {
  groups: [
    {
      key: "system",
      label: "시스템",
      tags: [
        { key: "system.title", label: "시스템명", type: "string", example: "가번호 관리 시스템" },
        { key: "system.printedAt", label: "출력일시", type: "string", example: "2026-09-12 09:30" },
      ],
    },
    {
      key: "school",
      label: "학교 정보",
      tags: [
        { key: "school.code", label: "학교코드", type: "string", example: "0000" },
        { key: "school.name", label: "학교명", type: "string", example: "한국대학교" },
      ],
    },
    {
      key: "candidate",
      label: "수험생 정보",
      tags: [
        { key: "candidate.examNo", label: "수험번호", type: "string", example: "20260001" },
        { key: "candidate.name", label: "성명", type: "string", example: "홍길동" },
        { key: "candidate.birthDate", label: "생년월일", type: "date", example: "2007-03-15" },
        { key: "candidate.temporaryNo", label: "가번호", type: "string", example: "1501" },
        { key: "candidate.preassignedNo", label: "사전 등록 가번호", type: "string", example: "1501" },
        { key: "candidate.examName", label: "시험명", type: "string", example: "2026년도 실기고사" },
        { key: "candidate.examDate", label: "시험일자", type: "date", example: "2026-09-12" },
        { key: "candidate.examStartTime", label: "시작시간", type: "time", example: "09:00" },
        { key: "candidate.examEndTime", label: "종료시간", type: "time", example: "11:00" },
        { key: "candidate.admissionYear", label: "모집년도", type: "string", example: "2026" },
        { key: "candidate.applicationTypeCode", label: "모집구분코드", type: "string", example: "1" },
        { key: "candidate.applicationTypeName", label: "모집구분", type: "string", example: "수시모집" },
        { key: "candidate.testTypeCode", label: "시험구분코드", type: "string", example: "1" },
        { key: "candidate.testTypeName", label: "시험구분", type: "string", example: "실기고사" },
        { key: "candidate.admissionTypeCode", label: "전형코드", type: "string", example: "A01" },
        { key: "candidate.admissionTypeName", label: "전형명", type: "string", example: "실기전형" },
        { key: "candidate.campusCode", label: "캠퍼스코드", type: "string", example: "SEOUL" },
        { key: "candidate.campusName", label: "캠퍼스명", type: "string", example: "서울캠퍼스" },
        { key: "candidate.collegeCode", label: "단과대코드", type: "string", example: "ART" },
        { key: "candidate.collegeName", label: "단과대명", type: "string", example: "예술대학" },
        { key: "candidate.seriesCode", label: "계열코드", type: "string", example: "ART" },
        { key: "candidate.seriesName", label: "계열명", type: "string", example: "예체능" },
        { key: "candidate.departmentCode", label: "모집단위코드", type: "string", example: "MUSIC" },
        { key: "candidate.departmentName", label: "모집단위명", type: "string", example: "음악학과" },
        { key: "candidate.majorCode", label: "전공코드", type: "string", example: "PIANO" },
        { key: "candidate.majorName", label: "전공명", type: "string", example: "피아노" },
        { key: "candidate.periodCode", label: "교시코드", type: "string", example: "P1" },
        { key: "candidate.periodName", label: "교시명", type: "string", example: "1교시" },
        { key: "candidate.groupName", label: "조", type: "string", example: "1조" },
        { key: "candidate.buildingCode", label: "고사장코드", type: "string", example: "B01" },
        { key: "candidate.buildingName", label: "고사장명", type: "string", example: "예술관" },
        { key: "candidate.roomCode", label: "고사실코드", type: "string", example: "R101" },
        { key: "candidate.roomName", label: "고사실명", type: "string", example: "101호" },
        { key: "candidate.seatNo", label: "좌석·순번", type: "string", example: "01" },
        { key: "candidate.absent", label: "결시 여부", type: "string", example: "응시" },
        { key: "candidate.photo", label: "수험생 사진", type: "image", example: "사진" },
        ...Array.from({ length: 3 }, (_, index) => ({
          key: `candidate.opt${index + 1}`,
          label: `옵션 ${index + 1}`,
          type: "string",
          example: `옵션값 ${index + 1}`,
        })),
      ],
    },
    {
      key: "room",
      label: "고사실 집계",
      tags: [
        { key: "room.assignedCount", label: "배정인원", type: "number", example: "24" },
        { key: "room.presentCount", label: "응시인원", type: "number", example: "22" },
        { key: "room.absentCount", label: "결시인원", type: "number", example: "2" },
      ],
    },
    {
      key: "etc",
      label: "기타",
      tags: [{ key: "row.indexInPage", label: "페이지 내 순번", type: "number", example: "1" }],
    },
  ],
} as const;
