CREATE TABLE IF NOT EXISTS candidate_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  designated_sort VARCHAR(100) NOT NULL DEFAULT '',
  track VARCHAR(200) NOT NULL,
  admission VARCHAR(200) NOT NULL,
  admission_code VARCHAR(100) NOT NULL,
  series VARCHAR(200) NOT NULL,
  series_code VARCHAR(100) NOT NULL DEFAULT '',
  unit_name VARCHAR(200) NOT NULL,
  unit_code VARCHAR(100) NOT NULL,
  major VARCHAR(200) NOT NULL DEFAULT '',
  major_code VARCHAR(100) NOT NULL DEFAULT '',
  exam_date DATE NOT NULL,
  start_time VARCHAR(5) NOT NULL,
  end_time VARCHAR(5) NOT NULL DEFAULT '',
  period_name VARCHAR(100) NOT NULL,
  period_code VARCHAR(100) NOT NULL,
  building_name VARCHAR(200) NOT NULL,
  building_code VARCHAR(100) NOT NULL,
  room_name VARCHAR(200) NOT NULL,
  room_code VARCHAR(100) NOT NULL,
  examinee_no VARCHAR(100) NOT NULL,
  temporary_no VARCHAR(100) NOT NULL DEFAULT '',
  name VARCHAR(100) NOT NULL,
  birth_date DATE NOT NULL,
  group_name VARCHAR(100) NOT NULL DEFAULT '',
  opt1 VARCHAR(500) NOT NULL DEFAULT '',
  opt2 VARCHAR(500) NOT NULL DEFAULT '',
  opt3 VARCHAR(500) NOT NULL DEFAULT '',
  opt4 VARCHAR(500) NOT NULL DEFAULT '',
  opt5 VARCHAR(500) NOT NULL DEFAULT '',
  opt6 VARCHAR(500) NOT NULL DEFAULT '',
  opt7 VARCHAR(500) NOT NULL DEFAULT '',
  opt8 VARCHAR(500) NOT NULL DEFAULT '',
  opt9 VARCHAR(500) NOT NULL DEFAULT '',
  opt10 VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_candidate_record_exam_period (examinee_no, period_code),
  KEY ix_candidate_record_name (name),
  KEY ix_candidate_record_exam_date (exam_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
