ALTER TABLE pseudonym_admission_lock COMMENT = '전형별 가번호 부여 동시 처리 잠금';
ALTER TABLE pseudonym_admission_lock MODIFY COLUMN exam_name VARCHAR(200) NOT NULL COMMENT '잠금 범위: exam_name';
ALTER TABLE pseudonym_admission_lock MODIFY COLUMN admission_name VARCHAR(200) NOT NULL COMMENT '잠금 범위: admission_name';
ALTER TABLE candidate_import_lock COMMENT = '수험번호별 등록 동시 처리 잠금';
ALTER TABLE candidate_import_lock MODIFY COLUMN examinee_no VARCHAR(100) NOT NULL COMMENT '잠금 범위: examinee_no';
ALTER TABLE pseudonym_operation_mutex COMMENT = '교시별 등록 및 운영 동시 처리 잠금';
ALTER TABLE pseudonym_operation_mutex MODIFY COLUMN exam_name VARCHAR(200) NOT NULL COMMENT '잠금 범위: exam_name';
ALTER TABLE pseudonym_operation_mutex MODIFY COLUMN exam_date DATE NOT NULL COMMENT '잠금 범위: exam_date';
ALTER TABLE pseudonym_operation_mutex MODIFY COLUMN exam_time VARCHAR(5) NOT NULL COMMENT '잠금 범위: exam_time';
ALTER TABLE pseudonym_operation_mutex MODIFY COLUMN period_name VARCHAR(100) NOT NULL COMMENT '잠금 범위: period_name';
ALTER TABLE pseudonym_operation_mutex MODIFY COLUMN admission_name VARCHAR(200) NOT NULL COMMENT '잠금 범위: admission_name';
ALTER TABLE candidate_upload_session COMMENT = '업로드 미리보기 및 등록 작업 상태';
ALTER TABLE candidate_upload_session MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '업로드 작업: id';
ALTER TABLE candidate_upload_session MODIFY COLUMN owner_id BIGINT UNSIGNED NOT NULL COMMENT '업로드 작업: owner_id';
ALTER TABLE candidate_upload_session MODIFY COLUMN kind ENUM('WORKBOOK','PHOTO_ARCHIVE') NOT NULL COMMENT '업로드 작업: kind';
ALTER TABLE candidate_upload_session MODIFY COLUMN status ENUM('PARSING','PREVIEW','QUEUED','RUNNING','SUCCEEDED','FAILED') NOT NULL COMMENT '업로드 작업: status';
ALTER TABLE candidate_upload_session MODIFY COLUMN file_name VARCHAR(255) NOT NULL COMMENT '업로드 작업: file_name';
ALTER TABLE candidate_upload_session MODIFY COLUMN checksum CHAR(64) NOT NULL COMMENT '업로드 작업: checksum';
ALTER TABLE candidate_upload_session MODIFY COLUMN state_checksum CHAR(64) NULL COMMENT '업로드 작업: state_checksum';
ALTER TABLE candidate_upload_session MODIFY COLUMN policy VARCHAR(32) NULL COMMENT '업로드 작업: policy';
ALTER TABLE candidate_upload_session MODIFY COLUMN preview_json LONGTEXT NULL COMMENT '업로드 작업: preview_json';
ALTER TABLE candidate_upload_session MODIFY COLUMN result_json LONGTEXT NULL COMMENT '업로드 작업: result_json';
ALTER TABLE candidate_upload_session MODIFY COLUMN error_message VARCHAR(1000) NULL COMMENT '업로드 작업: error_message';
ALTER TABLE candidate_upload_session MODIFY COLUMN processed INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '업로드 작업: processed';
ALTER TABLE candidate_upload_session MODIFY COLUMN total INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '업로드 작업: total';
ALTER TABLE candidate_upload_session MODIFY COLUMN expires_at DATETIME(3) NOT NULL COMMENT '업로드 작업: expires_at';
ALTER TABLE candidate_upload_session MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '업로드 작업: created_at';
ALTER TABLE candidate_upload_session MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '업로드 작업: updated_at';
